version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000      
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"
